# -*- coding: utf-8 -*-
"""PACS4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RqP1bOywhoaN2SUYC65pQVKERRdLMPLE
"""

!nvidia-smi

!pip install ultralytics
!pip install roboflow

import ultralytics
import os
from roboflow import Roboflow
from ultralytics import YOLO
from IPython.display import display,Image
from IPython import display
display.clear_output()
!yolo mode=checks

rf = Roboflow(api_key="Od5lGwnzWsFrsm9O2qoE")
project = rf.workspace("unistem").project("mun-voting-system")
dataset = project.version(4).download("yolov8")

!yolo task=detect mode=train  model=yolov8x.pt data={dataset.location}/data.yaml epochs=50 imgsz=640

Image(filename=f'/content/runs/detect/train6/confusion_matrix.png', width=1200)

Image(filename=f'/content/runs/detect/train6/confusion_matrix_normalized.png', width=1200)

Image(filename=f'/content/runs/detect/train6/results.png', width=1200)

!yolo task=detect mode=val model=/content/runs/detect/train6/weights/best.pt data={dataset.location}/data.yaml

!yolo task=detect mode=predict model=/content/runs/detect/train6/weights/best.pt conf=0.5 source={dataset.location}/test/images

import glob
from IPython.display import display,Image

for image_path in glob.glob(f'/content/runs/detect/predict/*.jpg'):
  display(Image(filename=image_path,height=600))
  print("\n")